import "./index.html";
import "./css/style.css";
import GAMESINFO from "./js/constants";
import { createBasketLength } from "./js/header/header";
import { clickCard, sortingCards, searchGameInStorage } from "./js/event";
import changeSliderPrice from "./js/sliders/sliderPrice";
import changeSliderRating from "./js/sliders/sliderRating";
import createSectionPresent from "./js/createSections/createSortingPresent";
import createTypeGameOption from "./js/createSections/createTypeGameSelect";
import createSortingGameOption from "./js/createSections/createSortingGameSelect";
import createCard from "./js/createCard";
import createSectionAmountPlayers from "./js/createSections/createAmountPlayers";
import createSearchButtonIcon from "./js/createSections/createButtonsSearch";
import { getinputValue } from "./js/search/search";

createBasketLength();
createTypeGameOption();
createSortingGameOption();
createSectionPresent();
changeSliderRating();
changeSliderPrice();
createSectionAmountPlayers();
createSearchButtonIcon(getinputValue);
createCard(GAMESINFO);
const mainFilters = document.querySelector(".main__filters") as HTMLElement;
mainFilters.addEventListener("change", sortingCards);
const sectionCards = document.querySelector(".section__cards") as HTMLElement;
sectionCards.addEventListener("click", clickCard);
window.addEventListener("input", searchGameInStorage);
